import { useEffect, useState } from 'react'
import { loadCorrespondence, submitQuestion } from '../lib/campaignCorrespondenceApi'

export function CampaignDispatches({ campaign }) {
  const [state, setState] = useState({ loading: true, messages: [] })
  useEffect(() => { let live = true; loadCorrespondence(campaign.slug).then((data) => { if (live) setState({ loading: false, messages: data.messages || [] }) }).catch(() => { if (live) setState({ loading: false, messages: [] }) }); return () => { live = false } }, [campaign.slug])
  return <section className="campaign-section campaign-section--dispatches" id="dispatches"><div className="campaign-shell"><div className="campaign-section-heading"><p>DIRECT FIELD PUBLISHING</p><div><h2>{campaign.sectionTitles?.dispatches || 'Dispatches'}</h2><p>Direct messages and preserved social posts remain available here independently of commercial platforms.</p></div></div>{state.loading ? <p>Loading dispatches…</p> : state.messages.length ? <div className="campaign-dispatch-list">{[...state.messages].reverse().map((message) => <article key={message.id}><header><strong>{message.displayName}</strong><time>{formatDate(message.originalPublishedAt || message.createdAt)}</time></header>{message.body ? <p>{message.body}</p> : null}<PublicMedia message={message} /><small>{message.originSource === 'instagram' ? <>Archived from <a href={message.originUrl} target="_blank" rel="noreferrer">@foodnotbombs_gaza on Instagram ↗</a></> : <>Published directly by {message.displayName}</>}</small></article>)}</div> : <div className="campaign-dispatch-empty"><strong>The independent channel is open.</strong><p>New text, audio, video, and preserved Instagram dispatches will appear here. Until then, use the verified fundraiser and original Instagram account linked below.</p></div>}</div></section>
}

export function CampaignQuestionForm({ campaign }) {
  // Sabot Media reviews submissions before anything reaches a contributor.
  const [values, setValues] = useState({ question: '', name: '', contact: '' }); const [state, setState] = useState('idle'); const [error, setError] = useState('')
  async function submit(event) { event.preventDefault(); setState('sending'); setError(''); try { await submitQuestion(campaign.slug, values); setValues({ question: '', name: '', contact: '' }); setState('sent') } catch (e) { setState('error'); setError(String(e.message || e)) } }
  return <section className="campaign-section campaign-section--questions" id="questions"><div className="campaign-shell campaign-question-layout"><div className="campaign-section-heading"><p>MODERATED PUBLIC QUESTIONS</p><div><h2>{campaign.sectionTitles?.questions || 'Ask the campaign'}</h2><p>Submit a respectful question. Sabot reviews submissions and may forward selected questions. Raw submissions are never sent directly to the contributor.</p></div></div><form onSubmit={submit}><label>Question<textarea required minLength="8" maxLength="2000" rows="5" value={values.question} onChange={(e) => setValues({ ...values, question: e.target.value })} /></label><div><label>Name or Anonymous<input maxLength="120" value={values.name} placeholder="Anonymous" onChange={(e) => setValues({ ...values, name: e.target.value })} /></label><label>Contact (optional)<input type="email" maxLength="240" value={values.contact} placeholder="Only for answer notification" onChange={(e) => setValues({ ...values, contact: e.target.value })} /></label></div><button className="campaign-button campaign-button--dark" disabled={state === 'sending'}>{state === 'sending' ? 'Sending…' : 'Submit question'}</button>{state === 'sent' ? <p role="status">Question received. Sabot will review it before anything is forwarded.</p> : null}{error ? <p role="alert">{error}</p> : null}</form></div></section>
}

export function CampaignDonation({ campaign }) {
  const donation = campaign.donation || {}; if (!donation.url) return null
  return <section className="campaign-section campaign-section--donate" id="donate"><div className="campaign-shell campaign-donation"><div><p>THE IMMEDIATE NEED</p><h2>{campaign.sectionTitles?.donate || 'Donate'}</h2><p>Food and other necessities may be available, but people need funds to obtain them under extreme and constantly changing conditions.</p></div><div className="campaign-donation__card"><span>VERIFIED DESTINATION</span><strong>{donation.recipient || campaign.shortTitle}</strong><p>{donation.explanation}</p><a className="campaign-button campaign-button--light" href={donation.url} target="_blank" rel="noreferrer">{donation.label || 'Donate'} ↗</a><small>Processed by {donation.platform || 'the named fundraiser'}, not Sabot Media. Sabot takes no percentage.{donation.lastVerifiedAt ? ` Link checked ${formatDate(donation.lastVerifiedAt)}.` : ''}</small></div></div></section>
}

export function CampaignBenefitToolkit({ campaign }) {
  const copy = `We are raising direct aid for Food Not Bombs Gaza, a Palestinian-led mutual-aid project preparing community meals for displaced families. Donations go through the campaign’s verified fundraiser. Learn more, hear field dispatches, and donate at https://sabot.media/campaigns/${campaign.slug}`
  return <section className="campaign-section campaign-section--benefit" id="benefit"><div className="campaign-shell"><div className="campaign-section-heading"><p>ORGANIZE WHERE YOU ARE</p><div><h2>{campaign.sectionTitles?.benefit || 'Benefit organizer toolkit'}</h2><p>Turn a show, meal, raffle, teach-in, community event, bookstore night, or chapter gathering into direct material support.</p></div></div><div className="campaign-benefit-grid"><article><span>01</span><h3>Use the stable campaign link</h3><p>Direct every poster, caption, and QR code to sabot.media/campaigns/{campaign.slug}.</p></article><article><span>02</span><h3>Say where money goes</h3><p>Tell attendees that donations use the verified {campaign.donation?.platform || 'fundraiser'} destination and Sabot takes no percentage.</p></article><article><span>03</span><h3>Send the result</h3><p>Report the date, city, event, and amount raised so the campaign can document material solidarity.</p></article></div><div className="campaign-benefit-copy"><h3>Copy-and-paste event description</h3><p>{copy}</p><button type="button" onClick={() => navigator.clipboard?.writeText(copy)}>Copy event text</button></div></div></section>
}
function PublicMedia({ message }) { if (!message.mediaUrl) return null; if (message.mediaType === 'audio') return <audio controls preload="metadata" src={message.mediaUrl} />; if (message.mediaType === 'video') return <video controls preload="metadata" playsInline src={message.mediaUrl} />; return <img loading="lazy" src={message.mediaUrl} alt="Field dispatch attachment" /> }
function formatDate(value) { try { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) } catch { return value } }
