import { getPrintlabElements } from './printlabElements.js'

const htmlStripper = /<[^>]*>/g
const preferredPrefixes = ['lucide', 'tabler', 'ph', 'material-symbols', 'heroicons', 'feather', 'bi', 'mdi', 'carbon', 'fluent']
const collectionLabels = {
  lucide: 'Lucide',
  tabler: 'Tabler Icons',
  ph: 'Phosphor Icons',
  'material-symbols': 'Material Symbols',
  heroicons: 'Heroicons',
  feather: 'Feather Icons',
  bi: 'Bootstrap Icons',
  mdi: 'Material Design Icons',
  carbon: 'Carbon Icons',
  fluent: 'Fluent UI Icons',
}

export const assetModeOptions = [
  { id: 'everything', label: 'Search Everything' },
  { id: 'elements', label: 'Elements' },
  { id: 'photos', label: 'Photos' },
  { id: 'illustrations', label: 'Illustrations' },
  { id: 'icons', label: 'Icons' },
  { id: 'historical', label: 'Historical' },
  { id: 'audio', label: 'Audio' },
  { id: 'textures', label: 'Textures' },
  { id: 'maps', label: 'Maps' },
  { id: 'documents', label: 'Documents' },
]

const profiles = {
  'mutual aid': {
    terms: ['mutual aid', 'solidarity', 'community', 'support', 'care', 'people', 'group', 'hands', 'heart', 'volunteer', 'food', 'box', 'home', 'house', 'medical', 'cross', 'megaphone', 'pantry'],
    icons: ['lucide:heart-handshake', 'lucide:hand-heart', 'lucide:users', 'lucide:handshake', 'lucide:house', 'lucide:package', 'lucide:utensils', 'lucide:soup', 'lucide:cross', 'lucide:megaphone', 'tabler:heart-handshake', 'tabler:users-group', 'tabler:home-heart', 'tabler:first-aid-kit', 'tabler:package', 'tabler:bowl-spoon', 'material-symbols:volunteer-activism', 'material-symbols:groups', 'material-symbols:home', 'material-symbols:medical-services', 'mdi:hand-heart', 'mdi:account-group', 'mdi:medical-bag'],
    local: ['Mutual Aid Notice Label', 'Free Food Label', 'Community Care Badge', 'Volunteer Needed Badge', 'Donation Box Label', 'Community Notice Label', 'Event Info Box'],
  },
  zine: {
    terms: ['zine', 'paper', 'photocopy', 'copy', 'scissors', 'tape', 'staple', 'paperclip', 'typewriter', 'newspaper', 'halftone', 'print', 'fold', 'cut', 'crop', 'collage', 'torn'],
    icons: ['lucide:scissors', 'lucide:paperclip', 'lucide:printer', 'lucide:file-text', 'lucide:copy', 'lucide:crop', 'tabler:scissors', 'tabler:paperclip', 'tabler:printer', 'mdi:scissors-cutting', 'mdi:paperclip', 'mdi:printer', 'material-symbols:content-cut', 'material-symbols:content-copy', 'material-symbols:print'],
    local: ['Zine Panel Frame', 'Photocopy Border', 'Torn Paper Strip', 'Tape Strip', 'Blackout Bar', 'Halftone Block', 'Fold Line', 'Cut Line', 'Crop Marks', 'Registration Marks'],
  },
  newspaper: {
    terms: ['newspaper', 'news', 'press', 'article', 'document', 'dispatch', 'byline', 'caption', 'archive', 'halftone'],
    icons: ['lucide:newspaper', 'lucide:file-text', 'tabler:news', 'tabler:article', 'mdi:newspaper', 'mdi:file-document-outline', 'material-symbols:newspaper', 'material-symbols:article', 'bi:newspaper', 'ph:newspaper'],
    local: ['Byline Strip', 'Caption Frame', 'Source Label', 'Dispatch Label', 'Archive Note Box', 'Pull Quote Frame', 'Halftone Block', 'Poster Headline Block'],
  },
  radio: {
    terms: ['radio', 'podcast', 'broadcast', 'signal', 'antenna', 'mic', 'microphone', 'audio', 'waveform', 'rss', 'headphones'],
    icons: ['lucide:radio', 'lucide:mic', 'lucide:podcast', 'lucide:rss', 'lucide:audio-lines', 'tabler:radio', 'tabler:microphone', 'tabler:podcast', 'mdi:radio', 'mdi:microphone', 'mdi:podcast', 'mdi:rss', 'material-symbols:radio', 'material-symbols:mic', 'material-symbols:rss-feed', 'bi:radio', 'bi:mic', 'bi:rss'],
    local: ['Audio Waveform Strip', 'Podcast Label', 'Radio Dispatch Badge', 'Dispatch Label'],
  },
  podcast: 'radio',
  dog: { terms: ['dog', 'pet', 'animal', 'paw', 'puppy'], icons: ['lucide:dog', 'lucide:paw-print', 'tabler:dog', 'tabler:paw', 'mdi:dog', 'mdi:dog-side', 'mdi:paw', 'material-symbols:pets'], local: [] },
  cat: { terms: ['cat', 'pet', 'animal', 'paw', 'kitten'], icons: ['lucide:cat', 'lucide:paw-print', 'tabler:cat', 'tabler:paw', 'mdi:cat', 'mdi:paw', 'material-symbols:pets'], local: [] },
  food: { terms: ['food', 'meal', 'bread', 'soup', 'bowl', 'apple', 'basket', 'box', 'pantry', 'kitchen', 'fork', 'spoon'], icons: ['lucide:utensils', 'lucide:soup', 'lucide:apple', 'lucide:package', 'tabler:bowl-spoon', 'tabler:bread', 'tabler:apple', 'mdi:food', 'mdi:bowl', 'mdi:food-apple', 'material-symbols:restaurant', 'bi:basket'], local: ['Free Food Label', 'Donation Box Label', 'Community Care Badge', 'Event Info Box'] },
  labor: { terms: ['labor', 'worker', 'union', 'tools', 'gear', 'wrench', 'hammer', 'factory', 'hands', 'people', 'banner', 'megaphone'], icons: ['lucide:wrench', 'lucide:hammer', 'lucide:settings', 'lucide:megaphone', 'tabler:tools', 'tabler:hammer', 'tabler:megaphone', 'mdi:wrench', 'mdi:hammer-wrench', 'mdi:factory', 'material-symbols:construction', 'material-symbols:factory'], local: ['Work Stoppage Notice Badge', 'Union Printer Mark', 'Poster Headline Block', 'Event Info Box'] },
  housing: { terms: ['housing', 'home', 'house', 'building', 'shelter', 'apartment'], icons: ['lucide:house', 'lucide:home', 'tabler:home', 'tabler:building-community', 'mdi:home', 'mdi:home-city', 'material-symbols:home', 'material-symbols:apartment'], local: ['Community Notice Label', 'Map Label', 'Event Info Box'] },
  medical: { terms: ['medical', 'health', 'cross', 'first aid', 'hospital', 'care', 'clinic'], icons: ['lucide:cross', 'lucide:heart-pulse', 'tabler:first-aid-kit', 'tabler:medical-cross', 'mdi:medical-bag', 'material-symbols:health-and-safety', 'material-symbols:medical-services'], local: ['Community Care Badge', 'Volunteer Needed Badge', 'Event Info Box'] },
  map: { terms: ['map', 'location', 'pin', 'marker', 'route'], icons: ['lucide:map', 'lucide:map-pin', 'lucide:navigation', 'tabler:map', 'tabler:map-pin', 'tabler:route', 'mdi:map', 'mdi:map-marker', 'material-symbols:map', 'material-symbols:location-on'], local: ['Map Label', 'Route Callout', 'Event Info Box'] },
  badge: { terms: ['badge', 'label', 'sticker', 'tag', 'notice'], icons: ['lucide:badge', 'lucide:tag', 'tabler:badge', 'tabler:tag', 'mdi:tag', 'material-symbols:label'], local: ['Free Food Label', 'Community Care Badge', 'Volunteer Needed Badge', 'Podcast Label', 'Radio Dispatch Badge'] },
  frame: { terms: ['frame', 'border', 'layout', 'box', 'panel'], icons: ['lucide:frame', 'lucide:square', 'tabler:frame', 'tabler:square', 'mdi:square-outline'], local: ['Event Info Box', 'Pull Quote Frame', 'Caption Frame', 'Zine Panel Frame', 'Photocopy Border', 'Field Note Box', 'Archive Note Box'] },
  arrow: { terms: ['arrow', 'line', 'divider', 'chevron', 'direction', 'pointer'], icons: ['lucide:arrow-right', 'lucide:arrow-up-right', 'lucide:corner-down-right', 'tabler:arrow-right', 'tabler:arrow-big-right', 'mdi:arrow-right', 'material-symbols:arrow-right-alt'], local: ['Route Callout'] },
  halftone: { terms: ['halftone', 'dots', 'print', 'texture', 'newspaper'], icons: ['lucide:circle-dot', 'tabler:circles', 'mdi:dots-grid', 'material-symbols:grain'], local: ['Halftone Block', 'Newspaper Halftone Strip', 'Photocopy Border'] },
  poster: { terms: ['poster', 'flyer', 'headline', 'event', 'notice', 'label', 'frame', 'megaphone'], icons: ['lucide:megaphone', 'lucide:calendar-days', 'lucide:map-pin', 'tabler:calendar-event', 'mdi:bullhorn', 'material-symbols:event'], local: ['Poster Headline Block', 'Event Info Box', 'Community Notice Label', 'Pull Quote Frame', 'Map Label'] },
  flyer: 'poster',
}

const localPackSeed = [
  ['Risograph Textures', 'textures', ['riso', 'risograph', 'texture', 'grain']],
  ['Photocopy Artifacts', 'textures', ['photocopy', 'xerox', 'noise', 'paper']],
  ['Fold Lines', 'textures', ['fold', 'paper', 'zine', 'layout']],
  ['Coffee Stains', 'textures', ['coffee', 'stain', 'paper', 'artifact']],
  ['Newspaper Halftones', 'textures', ['newspaper', 'halftone', 'print', 'dot']],
]

function clean(value = '') { return String(value || '').replace(htmlStripper, ' ').replace(/\s+/g, ' ').trim() }
function compactUrl(value = '') { return String(value || '').trim() }
function safeArray(value) { return Array.isArray(value) ? value : [] }
function safeNumber(value) { const number = Number(value); return Number.isFinite(number) && number > 0 ? number : null }
function uniqueValues(values = []) { const seen = new Set(); return values.map((value) => clean(value).toLowerCase()).filter((value) => value && !seen.has(value) && seen.add(value)) }
function splitWords(value = '') { return clean(value).split(/[^a-z0-9]+/i).filter((word) => word.length > 1) }
function titleCase(value = '') { return clean(value).replace(/[-_]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function resolveProfile(query = '') { const q = clean(query).toLowerCase(); const key = Object.keys(profiles).find((name) => q === name || q.includes(name)); const profile = profiles[key] || null; return typeof profile === 'string' ? profiles[profile] : profile }
function assetText(asset) { return [asset.title, asset.description, asset.category, asset.sourceLabel, ...(asset.tags || [])].join(' ').toLowerCase() }
function iconParts(icon = '') { const [prefix = '', name = ''] = clean(icon).split(':'); return { prefix, name, words: splitWords(name) } }
function iconBucket(value = '') { const text = clean(value).toLowerCase(); if (/arrow|chevron|corner|direction/.test(text)) return 'arrows'; if (/badge|label|tag|alert|warning/.test(text)) return 'labels'; if (/frame|square|circle|star|border/.test(text)) return 'layout'; if (/newspaper|article|file|document|book|archive/.test(text)) return 'editorial'; if (/radio|mic|podcast|rss|audio|wave/.test(text)) return 'media'; return 'icons' }

export function expandEditorialQuery(query = '') { const q = clean(query); const profile = resolveProfile(q); return uniqueValues([q, ...splitWords(q).filter((word) => word.length > 2), ...(profile?.terms || [])]) }
export function expandElementQuery(query = '') { return expandEditorialQuery(query) }

function inferMediaType(input = {}) { const mediaType = clean(input.mediaType || input.type || '').toLowerCase(); const mimeType = clean(input.mimeType || input.mime || '').toLowerCase(); const url = compactUrl(input.downloadUrl || input.previewUrl || input.thumbnailUrl || input.fullUrl || input.url); if (mediaType) return mediaType; if (mimeType.includes('svg') || /\.svg($|\?)/i.test(url)) return 'icon'; if (mimeType.startsWith('audio/')) return 'audio'; if (mimeType.includes('pdf') || /\.(pdf|docx?|txt)($|\?)/i.test(url)) return 'document'; return 'image' }
export function normalizePrintlabAsset(asset) { if (!asset || typeof asset !== 'object') return null; const downloadUrl = compactUrl(asset.downloadUrl || asset.fullUrl || asset.url || asset.previewUrl || asset.thumbnailUrl); const previewUrl = compactUrl(asset.previewUrl || asset.thumbnailUrl || downloadUrl); const thumbnailUrl = compactUrl(asset.thumbnailUrl || previewUrl || downloadUrl); const landingPageUrl = compactUrl(asset.landingPageUrl || asset.landingUrl || asset.foreignLandingUrl || ''); if (!downloadUrl && !previewUrl && !thumbnailUrl && !landingPageUrl) return null; const source = clean(asset.source || asset.originalProvider || 'external'); const sourceLabel = clean(asset.sourceLabel || asset.providerLabel || source || 'External'); const title = clean(asset.title || 'Untitled asset'); const creator = clean(asset.creator || ''); const license = clean(asset.license || ''); const licenseUrl = compactUrl(asset.licenseUrl || ''); const attributionText = clean(asset.attributionText || asset.attribution || [title, creator ? `by ${creator}` : '', sourceLabel, license].filter(Boolean).join(' / ')); const normalized = { id: String(asset.id || asset.originalId || `${source}:${downloadUrl || previewUrl || thumbnailUrl || landingPageUrl}`), title, creator, description: clean(asset.description || asset.caption || ''), thumbnailUrl, previewUrl, downloadUrl, landingPageUrl, license, licenseUrl, source, sourceLabel, mediaType: inferMediaType(asset), width: safeNumber(asset.width), height: safeNumber(asset.height), mimeType: clean(asset.mimeType || asset.mime || ''), attributionText, tags: uniqueValues(safeArray(asset.tags).length ? asset.tags : String(asset.tags || '').split(',')), category: clean(asset.category || ''), bucket: clean(asset.bucket || asset.category || ''), raw: asset.raw ?? asset, originalProvider: clean(asset.originalProvider || source), originalId: String(asset.originalId || asset.id || '') }; return { ...normalized, fullUrl: normalized.downloadUrl, url: normalized.downloadUrl, sourceName: normalized.sourceLabel, landingUrl: normalized.landingPageUrl, attribution: normalized.attributionText } }
function normalizeLocalMedia(item) { return normalizePrintlabAsset({ id: item?.id, originalProvider: item?.originalProvider || 'local-media', originalId: item?.originalId || item?.id, title: item?.title || item?.filename || 'Uploaded media', creator: item?.creator || '', description: item?.description || item?.caption || '', thumbnailUrl: item?.thumbnailUrl || item?.url || item?.dataUrl, previewUrl: item?.previewUrl || item?.url || item?.dataUrl, downloadUrl: item?.downloadUrl || item?.fullUrl || item?.url || item?.dataUrl, landingPageUrl: item?.landingPageUrl || item?.landingUrl || '', license: item?.license || '', licenseUrl: item?.licenseUrl || '', source: 'local-media', sourceLabel: item?.source && item.source !== 'local-upload' ? `Media Library / ${item.source}` : 'Sabot Media Library', mediaType: item?.mediaType || 'image', mimeType: item?.mimeType || '', attributionText: item?.attributionText || item?.attribution || item?.caption || '', category: item?.category || '', bucket: item?.bucket || '', tags: item?.tags || [], raw: item }) }
function normalizeIconify(input) { const icon = typeof input === 'string' ? input : input.icon; const { prefix, name, words } = iconParts(icon); if (!prefix || !name) return null; const collection = collectionLabels[prefix] || prefix; const svgUrl = `https://api.iconify.design/${encodeURIComponent(prefix)}/${encodeURIComponent(name)}.svg`; const title = titleCase(name.replace(/^ic-/, '').replace(/-\d+$/, '')); return normalizePrintlabAsset({ id: `iconify:${icon}`, originalProvider: 'iconify', originalId: icon, title, description: `${title} icon from ${collection}.`, thumbnailUrl: svgUrl, previewUrl: svgUrl, downloadUrl: svgUrl, source: 'iconify', sourceLabel: `Iconify / ${collection}`, creator: prefix, license: 'Icon set license varies', licenseUrl: 'https://iconify.design/docs/icons/license.html', attributionText: `${icon} icon from Iconify. Verify the ${collection} license before publication.`, mediaType: 'icon', mimeType: 'image/svg+xml', landingPageUrl: `https://icon-sets.iconify.design/${encodeURIComponent(prefix)}/${encodeURIComponent(name)}/`, tags: [prefix, collection, name, ...words, ...(input.tags || []), 'svg', 'icon', 'vector', 'element'], category: 'Icons', bucket: iconBucket(name), raw: input }) }
function packSvg(title, mode) { const initials = title.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420"><rect width="640" height="420" fill="#f6f1e8"/><rect x="34" y="34" width="572" height="352" fill="none" stroke="#1d2327" stroke-width="12"/><path d="M72 316h496M72 284h360M72 252h420" stroke="#c22b26" stroke-width="11"/><text x="72" y="132" font-family="Arial Black, Impact, sans-serif" font-size="82" fill="#1d2327">${initials}</text><text x="76" y="184" font-family="Arial, sans-serif" font-size="28" fill="#50575e">${mode.toUpperCase()}</text></svg>`; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}` }
function normalizeLocalPack([title, mode, tags], index) { const image = packSvg(title, mode); return normalizePrintlabAsset({ id: `local-pack:${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`, originalProvider: 'local-packs', originalId: title, title, creator: 'Sabot Media', description: 'Curated local asset pack placeholder.', thumbnailUrl: image, previewUrl: image, downloadUrl: image, source: 'local-packs', sourceLabel: 'Local Asset Packs', license: 'Internal curated asset', attributionText: `${title} local pack / Sabot Media`, mediaType: mode, mimeType: 'image/svg+xml', tags: [...tags, 'local pack', `pack-${index + 1}`], bucket: mode, raw: { title, mode, tags } }) }
function normalizeOpenverse(item) { const title = clean(item?.title || 'Untitled'); const creator = clean(item?.creator || ''); const license = clean(item?.license || ''); return normalizePrintlabAsset({ id: `openverse:${item?.id || item?.url || ''}`, originalProvider: 'openverse', originalId: item?.id || item?.url || '', title, thumbnailUrl: item?.thumbnail || item?.url, previewUrl: item?.thumbnail || item?.url, downloadUrl: item?.url || item?.thumbnail, source: 'openverse', sourceLabel: item?.source ? `Openverse / ${item.source}` : 'Openverse', creator, license, licenseUrl: item?.license_url, attributionText: clean(item?.attribution || [title, creator ? `by ${creator}` : '', license].filter(Boolean).join(' / ')), mediaType: 'photo', landingPageUrl: item?.foreign_landing_url, width: item?.width, height: item?.height, tags: [title, creator, item?.source], raw: item }) }
function normalizeCommons(page) { const info = page?.imageinfo?.[0] || {}; const title = clean(info?.extmetadata?.ObjectName?.value || page?.title || '').replace(/^File:/, ''); return normalizePrintlabAsset({ id: `wikimedia:${page.pageid || info.url}`, originalProvider: 'wikimedia', originalId: page.pageid || info.url || '', title, thumbnailUrl: info.thumburl || info.url, previewUrl: info.thumburl || info.url, downloadUrl: info.url || info.thumburl, source: 'wikimedia', sourceLabel: 'Wikimedia Commons', creator: clean(info.user || ''), license: clean(info?.extmetadata?.LicenseShortName?.value || ''), licenseUrl: compactUrl(info?.extmetadata?.LicenseUrl?.value || ''), attributionText: [title, info.user, 'Wikimedia Commons'].filter(Boolean).join(' / '), mediaType: String(info.mime || '').includes('svg') ? 'illustration' : 'photo', landingPageUrl: info.descriptionurl, mimeType: info.mime, width: info.width, height: info.height, tags: ['commons', 'historical', title], raw: page }) }
async function fetchJson(url) { const res = await fetch(url, { headers: { accept: 'application/json' } }); const data = await res.json().catch(() => null); if (!res.ok) throw new Error(data?.detail || data?.error || `Search failed: ${res.status}`); if (!data || typeof data !== 'object') throw new Error('Search returned an unreadable response.'); return data }
async function searchIconifyTerm(term, limit = 60) { const url = new URL('https://api.iconify.design/search'); url.searchParams.set('query', term); url.searchParams.set('limit', String(limit)); const data = await fetchJson(url); return safeArray(data.icons).filter((icon) => preferredPrefixes.includes(iconParts(icon).prefix)) }
function scoreIcon(icon, query, terms, profile) { const { prefix, name, words } = iconParts(typeof icon === 'string' ? icon : icon.icon); const text = [name, ...(icon.tags || [])].join(' ').toLowerCase(); let score = 120 - preferredPrefixes.indexOf(prefix) * 7; if (profile?.icons?.includes(`${prefix}:${name}`)) score += 500; if (profile?.terms?.some((term) => text.includes(term))) score += 100; const q = clean(query).toLowerCase(); if (q && (name === q || words.includes(q))) score += 160; if (q && name.includes(q)) score += 90; score += Math.min(90, terms.filter((term) => text.includes(term)).length * 18); if (!/arrow|line|direction|divider/i.test(q) && /arrow|chevron|caret/.test(name)) score -= 220; return score }
async function searchIconify(query, expandedTerms = []) { const cleanQuery = clean(query); const profile = resolveProfile(cleanQuery); const terms = uniqueValues([...expandElementQuery(cleanQuery), ...expandedTerms]); const icons = []; const seen = new Set(); profile?.icons?.forEach((icon) => { if (!seen.has(icon)) { seen.add(icon); icons.push({ icon, tags: profile.terms, curated: true }) } }); let firstError = null; for (const term of uniqueValues([cleanQuery, ...(profile?.terms || []), ...terms]).slice(0, 10)) { try { (await searchIconifyTerm(term, term === cleanQuery ? 90 : 30)).forEach((icon) => { if (!seen.has(icon)) { seen.add(icon); icons.push({ icon, tags: [term] }) } }) } catch (err) { if (!firstError) firstError = err } if (icons.length > 180) break } if (!icons.length && firstError) throw firstError; const prefixCounts = new Map(); const bucketCounts = new Map(); return icons.sort((a, b) => scoreIcon(b, cleanQuery, terms, profile) - scoreIcon(a, cleanQuery, terms, profile) || String(a.icon).localeCompare(String(b.icon))).filter((item) => { const icon = item.icon; const { prefix, name } = iconParts(icon); const bucket = iconBucket(name); const pc = prefixCounts.get(prefix) || 0; const bc = bucketCounts.get(bucket) || 0; if (pc >= 4) return false; if (!/arrow|line|direction|divider/i.test(cleanQuery) && bucket === 'arrows' && bc >= 2) return false; prefixCounts.set(prefix, pc + 1); bucketCounts.set(bucket, bc + 1); return true }).slice(0, 70) }
function modeMatches(asset, mode) { if (!asset || mode === 'everything') return true; const mediaType = clean(asset.mediaType).toLowerCase(); const text = assetText(asset); if (mode === 'elements') return ['iconify', 'printlab-elements'].includes(asset.source) || ['element', 'icon', 'illustration', 'graphic'].includes(mediaType); if (mode === 'photos') return ['photo', 'image'].includes(mediaType) || (mediaType === 'image' && asset.source !== 'iconify'); if (mode === 'illustrations') return ['illustration', 'graphic', 'element'].includes(mediaType) || ['woodcut', 'poster', 'graphic'].some((term) => text.includes(term)); if (mode === 'icons') return mediaType === 'icon' || asset.source === 'iconify'; if (mode === 'historical') return asset.source === 'wikimedia' || text.includes('historical'); if (mode === 'audio') return mediaType === 'audio'; if (mode === 'textures') return mediaType === 'texture' || ['texture', 'riso', 'photocopy', 'halftone', 'stain', 'fold'].some((term) => text.includes(term)); if (mode === 'maps') return mediaType === 'map' || text.includes('map'); if (mode === 'documents') return mediaType === 'document' || ['document', 'template', 'typewriter', 'wire'].some((term) => text.includes(term)); return true }
function textMatches(asset, terms) { return !terms.length || terms.some((term) => assetText(asset).includes(term)) }
function rank(asset, query, terms, mode) { const profile = resolveProfile(query); const text = assetText(asset); const title = clean(asset.title).toLowerCase(); const exact = clean(query).toLowerCase(); let score = 0; if (asset.source === 'printlab-elements') score += mode === 'elements' ? 260 : 130; if (asset.source === 'iconify') score += mode === 'elements' || mode === 'icons' ? 220 : 80; if (asset.source === 'local-media') score += 180; if (asset.source === 'local-packs') score += mode === 'elements' ? -200 : 20; if (profile?.local?.some((name) => title === name.toLowerCase())) score += 500; if (profile?.icons?.includes(asset.originalId)) score += 460; if (profile?.terms?.some((term) => text.includes(term))) score += 120; if (exact && title.includes(exact)) score += 90; score += Math.min(110, terms.filter((term) => text.includes(term)).length * 16); if (asset.source === 'openverse' || asset.source === 'wikimedia') score -= mode === 'everything' ? 35 : 15; if (!/arrow|line|direction|divider/i.test(exact) && /arrow|chevron/.test(text)) score -= 240; return score }
function dedupe(items) { const seen = new Set(); return items.filter((asset) => { const key = asset?.id || asset?.downloadUrl || asset?.previewUrl; if (!key || seen.has(key)) return false; seen.add(key); return true }) }
function diversify(items, query) { const q = clean(query).toLowerCase(); const sourceCounts = new Map(); const bucketCounts = new Map(); const first = []; const later = []; for (const asset of items) { const source = asset.source === 'iconify' ? asset.creator : asset.source; const bucket = asset.bucket || iconBucket(asset.originalId || asset.title); const sc = sourceCounts.get(source) || 0; const bc = bucketCounts.get(bucket) || 0; if (first.length < 45 && asset.source === 'iconify' && sc >= 4) { later.push(asset); continue } if (first.length < 45 && !/arrow|line|direction|divider/i.test(q) && bucket === 'arrows' && bc >= 2) { later.push(asset); continue } sourceCounts.set(source, sc + 1); bucketCounts.set(bucket, bc + 1); first.push(asset) } return [...first, ...later] }
const providers = [
  { id: 'printlab-elements', label: 'Printlab Elements', modes: ['everything', 'elements', 'illustrations', 'icons', 'textures', 'maps', 'documents'], async search({ query, expandedTerms, mode }) { const terms = mode === 'elements' ? expandElementQuery(query) : expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return getPrintlabElements().map(normalizePrintlabAsset).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
  { id: 'iconify', label: 'Iconify', modes: ['everything', 'elements', 'icons'], async search({ query, expandedTerms }) { if (!query) return []; return (await searchIconify(query, expandedTerms)).map(normalizeIconify).filter(Boolean) } },
  { id: 'local-media', label: 'Sabot Media Library', modes: ['everything', 'photos', 'illustrations', 'icons', 'audio', 'textures', 'maps', 'documents'], async search({ query, expandedTerms, mode, localMedia }) { const terms = expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return safeArray(localMedia).map(normalizeLocalMedia).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
  { id: 'local-packs', label: 'Local Asset Packs', modes: ['everything', 'illustrations', 'historical', 'textures', 'documents'], async search({ query, expandedTerms, mode }) { const terms = expandedTerms.length ? expandedTerms : expandEditorialQuery(query); return localPackSeed.map(normalizeLocalPack).filter(Boolean).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, terms)) } },
  { id: 'openverse', label: 'Openverse', modes: ['everything', 'photos', 'illustrations', 'textures'], async search({ query }) { if (!query) return []; const url = new URL('https://api.openverse.org/v1/images/'); url.searchParams.set('q', query); url.searchParams.set('page_size', '20'); const data = await fetchJson(url); return safeArray(data.results).map(normalizeOpenverse).filter(Boolean) } },
  { id: 'wikimedia', label: 'Wikimedia Commons', modes: ['everything', 'photos', 'illustrations', 'historical', 'maps', 'documents'], async search({ query }) { if (!query) return []; const url = new URL('https://commons.wikimedia.org/w/api.php'); url.searchParams.set('action', 'query'); url.searchParams.set('format', 'json'); url.searchParams.set('origin', '*'); url.searchParams.set('generator', 'search'); url.searchParams.set('gsrnamespace', '6'); url.searchParams.set('gsrlimit', '24'); url.searchParams.set('gsrsearch', query); url.searchParams.set('prop', 'imageinfo'); url.searchParams.set('iiprop', 'url|extmetadata|mime|user|size'); url.searchParams.set('iiurlwidth', '420'); const data = await fetchJson(url); const pages = data.query?.pages && typeof data.query.pages === 'object' ? Object.values(data.query.pages) : []; return pages.map(normalizeCommons).filter(Boolean) } },
]
export const assetProviders = providers.map(({ id, label, modes }) => ({ id, label, modes }))
function effectiveSources(sourceIds = [], mode = 'everything') { if (mode !== 'elements' || !sourceIds.length) return sourceIds; return sourceIds.includes('printlab-elements') && !sourceIds.includes('iconify') ? [] : sourceIds }
export async function searchUnifiedAssets({ query, mode = 'everything', sourceIds = [], localMedia = [] } = {}) { const cleanQuery = clean(query); const expandedTerms = mode === 'elements' ? expandElementQuery(cleanQuery) : expandEditorialQuery(cleanQuery); const activeSources = effectiveSources(sourceIds, mode); const activeProviders = providers.filter((provider) => (!activeSources.length || activeSources.includes(provider.id)) && (mode === 'everything' || provider.modes.includes(mode))); const settled = await Promise.all(activeProviders.map(async (provider) => { try { return { provider: { id: provider.id, label: provider.label }, results: safeArray(await provider.search({ query: cleanQuery, expandedTerms, mode, localMedia })).map(normalizePrintlabAsset).filter(Boolean), error: '' } } catch (err) { return { provider: { id: provider.id, label: provider.label }, results: [], error: String(err?.message || err || 'Provider failed.') } } })); const results = diversify(dedupe(settled.flatMap((entry) => entry.results)).filter((asset) => modeMatches(asset, mode)).filter((asset) => textMatches(asset, expandedTerms)).map((asset) => ({ ...asset, rank: rank(asset, cleanQuery, expandedTerms, mode) })).sort((a, b) => b.rank - a.rank || a.title.localeCompare(b.title)), cleanQuery); return { results, providers: settled.map((entry) => ({ id: entry.provider.id, label: entry.provider.label, count: entry.results.length, error: entry.error, state: entry.error ? 'error' : 'loaded' })), expandedTerms } }
export function importUrlAsset(rawUrl) { const downloadUrl = compactUrl(rawUrl); if (!downloadUrl) return null; let parsed = null; try { parsed = new URL(downloadUrl) } catch { throw new Error('Enter a valid URL.') } const filename = decodeURIComponent(parsed.pathname.split('/').pop() || '').replace(/\.[^.]+$/, ''); return normalizePrintlabAsset({ id: `url:${downloadUrl}`, originalProvider: 'url-import', originalId: downloadUrl, title: filename || parsed.hostname || 'URL import', thumbnailUrl: downloadUrl, previewUrl: downloadUrl, downloadUrl, source: 'url-import', sourceLabel: 'URL Import', creator: parsed.hostname, license: 'Unknown', attributionText: `Imported from ${parsed.hostname}. Add creator/license metadata before publication.`, mediaType: /\.svg($|\?)/i.test(parsed.pathname) ? 'icon' : 'image', landingPageUrl: downloadUrl }) }
export async function searchAssetSource(sourceId, query, options = {}) { const data = await searchUnifiedAssets({ query, mode: options.mode || 'everything', sourceIds: [sourceId], localMedia: options.localMedia || [] }); const providerState = data.providers.find((provider) => provider.id === sourceId); if (providerState?.error) throw new Error(providerState.error); return data.results }
